# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
# Some references
#	https://github.com/ropenscilabs/umapr/blob/master/.travis.yml

language: R
sudo: true
cache: packages

os:
  - linux

addons:
  apt:
    packages:
      - cmake
      - glpk-utils
      - libmpfr-dev
      - xorg
      - libx11-dev
      - libglu1-mesa-dev
      - libfreetype6-dev
      - libgdal-dev 
      - libgeos-dev 
      - gdal-bin 
      - proj-bin
      - libproj-dev
      - cargo
      - libstd-rust-dev
      - rust-gdb
      - rustc

r:
  - release

r-packages:
	- ADMM
  - MASS
  - CVXR
  - Rcpp
  - RcppDE
  - RcppDist
  - RcppArmadillo
  - Rdpack
  - RSpectra
  - maotai
  - knitr
  - rmarkdown
  - Rdpack

env:
  global:
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --ignore-vignettes --no-examples"
    - R_BUILD_ARGS="--no-build-vignettes"

warnings_are_errors: false
