# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

aux_preprocess <- function(X, flag) {
    .Call('_Rdimtools_aux_preprocess', PACKAGE = 'Rdimtools', X, flag)
}

aux_perplexity <- function(X, perplexity) {
    .Call('_Rdimtools_aux_perplexity', PACKAGE = 'Rdimtools', X, perplexity)
}

aux_shortestpath <- function(wmat) {
    .Call('_Rdimtools_aux_shortestpath', PACKAGE = 'Rdimtools', wmat)
}

aux_landmarkMaxMin <- function(pD, plandmark, seqnp) {
    .Call('_Rdimtools_aux_landmarkMaxMin', PACKAGE = 'Rdimtools', pD, plandmark, seqnp)
}

aux_kernelcov <- function(tX, knumber, par1, par2) {
    .Call('_Rdimtools_aux_kernelcov', PACKAGE = 'Rdimtools', tX, knumber, par1, par2)
}

aux_eigendecomposition <- function(X) {
    .Call('_Rdimtools_aux_eigendecomposition', PACKAGE = 'Rdimtools', X)
}

aux_minmax <- function(X, gap) {
    .Call('_Rdimtools_aux_minmax', PACKAGE = 'Rdimtools', X, gap)
}

aux_regout <- function(X, tgt) {
    .Call('_Rdimtools_aux_regout', PACKAGE = 'Rdimtools', X, tgt)
}

#' @keywords internal
methods_boxcount <- function(tX, Imin, currentr) {
    .Call('_Rdimtools_methods_boxcount', PACKAGE = 'Rdimtools', tX, Imin, currentr)
}

#' @keywords internal
aux_numderiv <- function(x, y) {
    .Call('_Rdimtools_aux_numderiv', PACKAGE = 'Rdimtools', x, y)
}

#' @keywords internal
method_pca <- function(psdX) {
    .Call('_Rdimtools_method_pca', PACKAGE = 'Rdimtools', psdX)
}

#' @keywords internal
method_mds <- function(centerX) {
    .Call('_Rdimtools_method_mds', PACKAGE = 'Rdimtools', centerX)
}

#' @keywords internal
method_mdsD <- function(D) {
    .Call('_Rdimtools_method_mdsD', PACKAGE = 'Rdimtools', D)
}

#' @keywords internal
method_ica <- function(X, C, maxiter, tol, tnum, tpar, sym) {
    .Call('_Rdimtools_method_ica', PACKAGE = 'Rdimtools', X, C, maxiter, tol, tnum, tpar, sym)
}

#' @keywords internal
method_rpgauss <- function(X, k) {
    .Call('_Rdimtools_method_rpgauss', PACKAGE = 'Rdimtools', X, k)
}

#' @keywords internal
method_fa <- function(X, k, maxiter, tolerance) {
    .Call('_Rdimtools_method_fa', PACKAGE = 'Rdimtools', X, k, maxiter, tolerance)
}

method_lpp <- function(X, W) {
    .Call('_Rdimtools_method_lpp', PACKAGE = 'Rdimtools', X, W)
}

#' @keywords internal
method_npe <- function(X, W) {
    .Call('_Rdimtools_method_npe', PACKAGE = 'Rdimtools', X, W)
}

#' @keywords internal
method_olpp <- function(X, S, ndim) {
    .Call('_Rdimtools_method_olpp', PACKAGE = 'Rdimtools', X, S, ndim)
}

#' @keywords internal
method_bpca <- function(T, reltol, maxiter) {
    .Call('_Rdimtools_method_bpca', PACKAGE = 'Rdimtools', T, reltol, maxiter)
}

#' @keywords internal
NULL

#' @keywords internal
NULL

#' @keywords internal
method_sne <- function(P, ndim, eta, maxiter, jitter, decay, momentum) {
    .Call('_Rdimtools_method_sne', PACKAGE = 'Rdimtools', P, ndim, eta, maxiter, jitter, decay, momentum)
}

#' @keywords internal
method_snesym <- function(P, ndim, eta, maxiter, jitter, decay, momentum) {
    .Call('_Rdimtools_method_snesym', PACKAGE = 'Rdimtools', P, ndim, eta, maxiter, jitter, decay, momentum)
}

#' @keywords internal
method_tsne <- function(P, ndim, eta, maxiter, jitter, decay, momentum) {
    .Call('_Rdimtools_method_tsne', PACKAGE = 'Rdimtools', P, ndim, eta, maxiter, jitter, decay, momentum)
}

#' @keywords internal
method_eigenmaps <- function(W) {
    .Call('_Rdimtools_method_eigenmaps', PACKAGE = 'Rdimtools', W)
}

#' @keywords internal
method_sammon <- function(X, Yinit) {
    .Call('_Rdimtools_method_sammon', PACKAGE = 'Rdimtools', X, Yinit)
}

#' @keywords internal
method_lleW <- function(mat_tgt, vec_tgt, regparam) {
    .Call('_Rdimtools_method_lleW', PACKAGE = 'Rdimtools', mat_tgt, vec_tgt, regparam)
}

#' @keywords internal
method_lleWauto <- function(mat_tgt, vec_tgt) {
    .Call('_Rdimtools_method_lleWauto', PACKAGE = 'Rdimtools', mat_tgt, vec_tgt)
}

#' @keywords internal
method_lleM <- function(W) {
    .Call('_Rdimtools_method_lleM', PACKAGE = 'Rdimtools', W)
}

#' @keywords internal
method_ree <- function(B, W, D, initc, abstol, maxiter) {
    .Call('_Rdimtools_method_ree', PACKAGE = 'Rdimtools', B, W, D, initc, abstol, maxiter)
}

