# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

aux_preprocess <- function(X, flag) {
    .Call(`_Rdimtools_aux_preprocess`, X, flag)
}

aux_perplexity <- function(X, perplexity) {
    .Call(`_Rdimtools_aux_perplexity`, X, perplexity)
}

aux_shortestpath <- function(wmat) {
    .Call(`_Rdimtools_aux_shortestpath`, wmat)
}

aux_landmarkMaxMin <- function(pD, plandmark, seqnp) {
    .Call(`_Rdimtools_aux_landmarkMaxMin`, pD, plandmark, seqnp)
}

aux_kernelcov <- function(tX, knumber, par1, par2) {
    .Call(`_Rdimtools_aux_kernelcov`, tX, knumber, par1, par2)
}

aux_eigendecomposition <- function(X) {
    .Call(`_Rdimtools_aux_eigendecomposition`, X)
}

aux_minmax <- function(X, gap) {
    .Call(`_Rdimtools_aux_minmax`, X, gap)
}

aux_regout <- function(X, tgt) {
    .Call(`_Rdimtools_aux_regout`, X, tgt)
}

aux_scatter <- function(X, mu) {
    .Call(`_Rdimtools_aux_scatter`, X, mu)
}

aux_scatter_pairwise <- function(X) {
    .Call(`_Rdimtools_aux_scatter_pairwise`, X)
}

aux_geigen <- function(A, B) {
    .Call(`_Rdimtools_aux_geigen`, A, B)
}

#' @keywords internal
#' @noRd
linsolve.bicgstab.single <- function(A, b, xinit, reltol, maxiter, M) {
    .Call(`_Rdimtools_single_bicgstab`, A, b, xinit, reltol, maxiter, M)
}

#' @keywords internal
#' @noRd
linsolve.bicgstab.single.sparse <- function(A, b, xinit, reltol, maxiter, M) {
    .Call(`_Rdimtools_single_bicgstab_sparse`, A, b, xinit, reltol, maxiter, M)
}

aux_expm <- function(A) {
    .Call(`_Rdimtools_aux_expm`, A)
}

aux_rank <- function(A) {
    .Call(`_Rdimtools_aux_rank`, A)
}

methods_boxcount <- function(tX, Imin, currentr) {
    .Call(`_Rdimtools_methods_boxcount`, tX, Imin, currentr)
}

aux_numderiv <- function(x, y) {
    .Call(`_Rdimtools_aux_numderiv`, x, y)
}

handy_plus <- function(X) {
    .Call(`_Rdimtools_handy_plus`, X)
}

handy_hadamardABC <- function(A, B, C) {
    .Call(`_Rdimtools_handy_hadamardABC`, A, B, C)
}

handy_hadamardABCsqrt <- function(A, B, C) {
    .Call(`_Rdimtools_handy_hadamardABCsqrt`, A, B, C)
}

#' @keywords internal
NULL

#' @keywords internal
method_pca <- function(psdX) {
    .Call(`_Rdimtools_method_pca`, psdX)
}

#' @keywords internal
method_mds <- function(centerX) {
    .Call(`_Rdimtools_method_mds`, centerX)
}

#' @keywords internal
method_mdsD <- function(D) {
    .Call(`_Rdimtools_method_mdsD`, D)
}

#' @keywords internal
method_ica <- function(X, C, maxiter, tol, tnum, tpar, sym) {
    .Call(`_Rdimtools_method_ica`, X, C, maxiter, tol, tnum, tpar, sym)
}

#' @keywords internal
method_rpgauss <- function(X, k) {
    .Call(`_Rdimtools_method_rpgauss`, X, k)
}

method_fa <- function(X, k, maxiter, tolerance) {
    .Call(`_Rdimtools_method_fa`, X, k, maxiter, tolerance)
}

#' @keywords internal
method_npe <- function(X, W) {
    .Call(`_Rdimtools_method_npe`, X, W)
}

#' @keywords internal
method_olpp <- function(X, S, ndim) {
    .Call(`_Rdimtools_method_olpp`, X, S, ndim)
}

#' @keywords internal
method_bpca <- function(T, reltol, maxiter) {
    .Call(`_Rdimtools_method_bpca`, T, reltol, maxiter)
}

#' @keywords internal
method_trfextlpp <- function(D, a, b) {
    .Call(`_Rdimtools_method_trfextlpp`, D, a, b)
}

#' @keywords internal
method_lspp_computeW <- function(S, svec) {
    .Call(`_Rdimtools_method_lspp_computeW`, S, svec)
}

#' @keywords internal
method_kmmcvec <- function(X, partmat, param) {
    .Call(`_Rdimtools_method_kmmcvec`, X, partmat, param)
}

#' @keywords internal
method_lfda_maximaldistance <- function(tvec, tmat) {
    .Call(`_Rdimtools_method_lfda_maximaldistance`, tvec, tmat)
}

#' @keywords internal
method_nnprojmax <- function(C, Uinit, tol, maxiter) {
    .Call(`_Rdimtools_method_nnprojmax`, C, Uinit, tol, maxiter)
}

#' @keywords internal
method_nnprojmin <- function(C, Uinit, tol, maxiter) {
    .Call(`_Rdimtools_method_nnprojmin`, C, Uinit, tol, maxiter)
}

#' @keywords internal
method_nnembedmin <- function(M, Yinit, tol, maxiter) {
    .Call(`_Rdimtools_method_nnembedmin`, M, Yinit, tol, maxiter)
}

#' @keywords internal
method_spufs <- function(X, Ls, alpha, beta, epsilon) {
    .Call(`_Rdimtools_method_spufs`, X, Ls, alpha, beta, epsilon)
}

#' @keywords internal
method_lspe <- function(X, d, alpha, beta, L) {
    .Call(`_Rdimtools_method_lspe`, X, d, alpha, beta, L)
}

method_disr <- function(D, lbd1, lbd2) {
    .Call(`_Rdimtools_method_disr`, D, lbd1, lbd2)
}

#' @keywords internal
method_rsr <- function(X, lbd, verysmall) {
    .Call(`_Rdimtools_method_rsr`, X, lbd, verysmall)
}

#' @keywords internal
method_nrsr <- function(X, lbd, verysmall, p) {
    .Call(`_Rdimtools_method_nrsr`, X, lbd, verysmall, p)
}

method_scoresum <- function(X, S) {
    .Call(`_Rdimtools_method_scoresum`, X, S)
}

method_lsls <- function(X, nbd) {
    .Call(`_Rdimtools_method_lsls`, X, nbd)
}

method_sne <- function(P, ndim0, eta0, maxiter0, jitter0, decay0, momentum0) {
    .Call(`_Rdimtools_method_sne`, P, ndim0, eta0, maxiter0, jitter0, decay0, momentum0)
}

method_snesym <- function(P, ndim0, eta0, maxiter0, jitter0, decay0, momentum0) {
    .Call(`_Rdimtools_method_snesym`, P, ndim0, eta0, maxiter0, jitter0, decay0, momentum0)
}

method_tsne <- function(P, ndim0, eta0, maxiter0, jitter0, decay0, momentum0) {
    .Call(`_Rdimtools_method_tsne`, P, ndim0, eta0, maxiter0, jitter0, decay0, momentum0)
}

method_eigenmaps <- function(W) {
    .Call(`_Rdimtools_method_eigenmaps`, W)
}

method_sammon <- function(X, Yinit) {
    .Call(`_Rdimtools_method_sammon`, X, Yinit)
}

method_lleW <- function(mat_tgt, vec_tgt, regparam) {
    .Call(`_Rdimtools_method_lleW`, mat_tgt, vec_tgt, regparam)
}

method_lleWauto <- function(mat_tgt, vec_tgt) {
    .Call(`_Rdimtools_method_lleWauto`, mat_tgt, vec_tgt)
}

method_lleM <- function(W) {
    .Call(`_Rdimtools_method_lleM`, W)
}

method_ree <- function(B, W, D, initc, abstol, maxiter) {
    .Call(`_Rdimtools_method_ree`, B, W, D, initc, abstol, maxiter)
}

method_spe <- function(R, iX, C, S, lambda, drate, matselector) {
    .Call(`_Rdimtools_method_spe`, R, iX, C, S, lambda, drate, matselector)
}

method_ispe <- function(R, iX, C, S, lambda, drate, matselector, cutoff) {
    .Call(`_Rdimtools_method_ispe`, R, iX, C, S, lambda, drate, matselector, cutoff)
}

method_crca <- function(Xij, Yinit, lambda, alpha, maxiter, tolerance, vecselector) {
    .Call(`_Rdimtools_method_crca`, Xij, Yinit, lambda, alpha, maxiter, tolerance, vecselector)
}

bmds_compute_SSR <- function(D, Delta) {
    .Call(`_Rdimtools_bmds_compute_SSR`, D, Delta)
}

main_bmds <- function(D, X0, sigg0, a, alpha, maxiter, constant, verbose, betas) {
    .Call(`_Rdimtools_main_bmds`, D, X0, sigg0, a, alpha, maxiter, constant, verbose, betas)
}

dt_pca <- function(X, ndim, ptype, cor) {
    .Call(`_Rdimtools_dt_pca`, X, ndim, ptype, cor)
}

dt_fa <- function(X, ndim, ptype, maxiter, tolerance) {
    .Call(`_Rdimtools_dt_fa`, X, ndim, ptype, maxiter, tolerance)
}

dt_spca <- function(X, ndim, ptype, mu, rho, abstol, reltol, maxiter) {
    .Call(`_Rdimtools_dt_spca`, X, ndim, ptype, mu, rho, abstol, reltol, maxiter)
}

dt_mds <- function(X, ndim, ptype) {
    .Call(`_Rdimtools_dt_mds`, X, ndim, ptype)
}

admm_lasso <- function(A, b, lambda) {
    .Call(`_Rdimtools_admm_lasso`, A, b, lambda)
}

dt_lasso <- function(X, ndim, ptype, y, ycenter, lambda) {
    .Call(`_Rdimtools_dt_lasso`, X, ndim, ptype, y, ycenter, lambda)
}

dt_enet <- function(X, ndim, ptype, y, ycenter, lambda1, lambda2) {
    .Call(`_Rdimtools_dt_enet`, X, ndim, ptype, y, ycenter, lambda1, lambda2)
}

dt_lmds <- function(X, ndim, ptype, npts) {
    .Call(`_Rdimtools_dt_lmds`, X, ndim, ptype, npts)
}

dt_rpca <- function(X, ndim, ptype, mu, lambda) {
    .Call(`_Rdimtools_dt_rpca`, X, ndim, ptype, mu, lambda)
}

